name: CI Notice

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - uses: actions-cool/ci-notice@main
        with:
          ci: |
            npm install pnpm@latest-8 -g
            pnpm install
            pnpm run build
            node index.js
          notice-types: 'issue'
          issue-assignees: 'Wxh16144'
